baseURL = "//jessemalone.com/"
languageCode = "en-us"
title = "Jesse Malone"
theme = "hugo-initio"

[markup.goldmark.renderer]
unsafe= true

[params]
        name = "Jesse Malone"
        description = "Musician | Software Engineer"
        email = "jesse.malone at gmail dot com"
        year = 2019
        avatar = "images/circlephoto.jpg"
        background = ""
        favicon = "images/vger_favicon.png"
        DateForm = "January 2, 2006"

        showSubheader = true
        showServices = false
        showAbout = true
        showRecentWorks = false
        showDownload = false
        showClients = false

        footerEnableContact = true
        footerEnableFollowme = true
        footerEnableTextWidget = false
        footerEnableFormWidget = true

[[menu.main]]
  name = "home"
  url = "#!/home"
  weight = 1


[[menu.main]]
  name = "shows"
  url = "#!/events"
  weight = 3

[[menu.main]]
  name = "projects"
  url = "#!/projects"
  weight = 4

[[params.social]]
	title = "linkedin"
	url = "https://ca.linkedin.com/in/jesse-malone-29970a14"
    icon = "fa-linkedin"
    footer = true
    sharethis = false
    network = ""

[[params.social]]
	title = "soundcloud"
	url = "https://soundcloud.com/jessemalone"
    icon = "fa-soundcloud"
    footer = true
    sharethis = false
    network = ""


[params.google.analytics]
    trackerID = "UA-145233480-1"
